# Generated by Django 6.0.4 on 2026-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCBJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('gerber_file', models.FileField(upload_to='gerber_files/')),
                ('gcode_file', models.FileField(blank=True, null=True, upload_to='gcode_output/')),
                ('preview_img', models.ImageField(blank=True, null=True, upload_to='previews/')),
                ('width_mm', models.FloatField(blank=True, null=True)),
                ('height_mm', models.FloatField(blank=True, null=True)),
                ('area_mm2', models.FloatField(blank=True, null=True)),
                ('price_bs', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSING', 'Procesando G-code'), ('READY', 'Listo para enviar'), ('SENDING', 'Enviando a CNC'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='RECEIVED', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
