# Generated by Django 6.0.4 on 2026-05-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcbjob',
            name='gerber_file',
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='outline_file',
            field=models.FileField(blank=True, null=True, upload_to='gerber_files/'),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='outline_gcode',
            field=models.FileField(blank=True, null=True, upload_to='gcode_output/'),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='pads_file',
            field=models.FileField(blank=True, null=True, upload_to='gerber_files/'),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='pads_gcode',
            field=models.FileField(blank=True, null=True, upload_to='gcode_output/'),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='traces_file',
            field=models.FileField(blank=True, null=True, upload_to='gerber_files/'),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='traces_gcode',
            field=models.FileField(blank=True, null=True, upload_to='gcode_output/'),
        ),
    ]
