# Generated by Django 6.0.4 on 2026-05-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pcbjob_gerber_file_pcbjob_outline_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbjob',
            name='alias',
            field=models.CharField(blank=True, help_text='Nombre del diseñador o proyecto', max_length=100, null=True),
        ),
    ]
