# Generated by Django 6.0.4 on 2026-05-02 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pcbjob_publication_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.FloatField(help_text='Ancho de la lámina en mm')),
                ('height', models.FloatField(help_text='Alto de la lámina en mm')),
                ('free_areas', models.JSONField(blank=True, default=list)),
                ('used_areas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='margin_mm',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='placement_height',
            field=models.FloatField(blank=True, help_text='Alto incluyendo margen', null=True),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='placement_width',
            field=models.FloatField(blank=True, help_text='Ancho incluyendo margen', null=True),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='placement_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='placement_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcbjob',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Recibido'), ('PANELIZING', 'Panelizando'), ('PROCESSING', 'Procesando G-code'), ('READY', 'Listo para enviar'), ('SENDING', 'Enviando a CNC'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='RECEIVED', max_length=20),
        ),
        migrations.AddField(
            model_name='pcbjob',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.sheet'),
        ),
    ]
