# Generated by Django 6.0.4 on 2026-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sheet_pcbjob_margin_mm_pcbjob_placement_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbjob',
            name='active_gcode_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
